# This is a separate file because the lockscreen wallpaper will be changed based on the current wallpaper.
# To avoid lockscreen wallpaper changes from showing up in the commit history, it has been added to .gitginore.

background {
    path = /home/tanay/.dotfiles/wallpapers/Pictures/Wallpapers/53156738-castle-landscape-3840-x-2160-r.jpg
    blur_size = 5
    blur_passes = 2
}
