swipe:
  3:
    begin:
      command: ydotool click 40
      interval: 0.00
    update:
      command: ydotool mousemove -- $move_x, $move_y
      interval: 0.01
      accel: 1.70
    end:
      command: ydotool click 80
